"""
ML Pipeline Generator
Automatically generates scikit-learn preprocessing pipelines
"""

import pandas as pd
import numpy as np
from typing import Dict, Any, List
import warnings
warnings.filterwarnings('ignore')


class PipelineGenerator:
    """Generates ML preprocessing pipelines"""
    
    def __init__(self, df: pd.DataFrame, target_column: str = None, analysis_data: Dict[str, Any] = None):
        """
        Initialize pipeline generator
        
        Args:
            df: Input DataFrame
            target_column: Target column name
            analysis_data: Analysis results for optimization
        """
        self.df = df
        self.target_column = target_column
        self.analysis_data = analysis_data or {}
        self.numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        self.categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
    
    def generate_pipeline_code(self) -> Dict[str, Any]:
        """
        Generate optimized ML preprocessing pipeline code
        
        Returns:
            Pipeline code and documentation
        """
        imports = self._get_imports()
        numeric_pipeline = self._generate_numeric_pipeline()
        categorical_pipeline = self._generate_categorical_pipeline()
        final_pipeline = self._generate_final_pipeline()
        example_usage = self._generate_example_usage()
        
        complete_code = self._combine_code(
            imports,
            numeric_pipeline,
            categorical_pipeline,
            final_pipeline,
            example_usage
        )
        
        return {
            'status': 'success',
            'pipeline_code': complete_code,
            'numeric_features': self.numeric_cols,
            'categorical_features': self.categorical_cols,
            'steps': self._get_pipeline_steps(),
            'example_usage': example_usage
        }
    
    def _get_imports(self) -> str:
        """Generate import statements"""
        return '''"""
Auto-generated ML Pipeline
Generated by DATA DOCTOR
"""

import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline, ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_selector
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
'''
    
    def _generate_numeric_pipeline(self) -> str:
        """Generate numeric feature pipeline"""
        if not self.numeric_cols:
            return "# No numeric features detected"
        
        code = '''
# ============================================
# NUMERIC FEATURES PIPELINE
# ============================================

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),  # Fill missing with median
    ('scaler', StandardScaler())                     # Normalize to mean=0, std=1
])
'''
        return code
    
    def _generate_categorical_pipeline(self) -> str:
        """Generate categorical feature pipeline"""
        if not self.categorical_cols:
            return "# No categorical features detected"
        
        code = '''
# ============================================
# CATEGORICAL FEATURES PIPELINE
# ============================================

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),  # Fill with mode
    ('onehot', OneHotEncoder(handle_unknown='ignore'))     # One-Hot Encoding
])
'''
        return code
    
    def _generate_final_pipeline(self) -> str:
        """Generate final combined pipeline"""
        numeric_list = [f"'{col}'" for col in self.numeric_cols]
        numeric_code = f"[{', '.join(numeric_list)}]" if numeric_list else "[]"
        categorical_list = [f"'{col}'" for col in self.categorical_cols]
        categorical_code = f"[{', '.join(categorical_list)}]" if categorical_list else "[]"
        
        code = f'''
# ============================================
# COMBINED PREPROCESSING PIPELINE
# ============================================

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, {numeric_code}),
        ('cat', categorical_transformer, {categorical_code})
    ],
    remainder='drop'  # Drop any remaining columns
)

# Full pipeline with model
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestClassifier(n_estimators=100, random_state=42))
    # Use RandomForestRegressor for regression tasks
])
'''
        return code
    
    def _generate_example_usage(self) -> str:
        """Generate example usage code"""
        code = '''
# ============================================
# EXAMPLE USAGE
# ============================================

# 1. Load data
# X = pd.read_csv('dataset.csv').drop('target', axis=1)
# y = pd.read_csv('dataset.csv')['target']

# 2. Split data
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Fit pipeline
# pipeline.fit(X_train, y_train)

# 4. Make predictions
# predictions = pipeline.predict(X_test)

# 5. Evaluate
# from sklearn.metrics import accuracy_score, classification_report
# print(f"Accuracy: {accuracy_score(y_test, predictions):.4f}")
# print(classification_report(y_test, predictions))

# 6. Save pipeline
# import pickle
# with open('pipeline.pkl', 'wb') as f:
#     pickle.dump(pipeline, f)

# 7. Load and use pipeline
# with open('pipeline.pkl', 'rb') as f:
#     loaded_pipeline = pickle.load(f)
# new_predictions = loaded_pipeline.predict(new_data)
'''
        return code
    
    def _combine_code(self, *code_parts) -> str:
        """Combine all code parts"""
        return '\n'.join(code_parts)
    
    def _get_pipeline_steps(self) -> List[Dict]:
        """Describe pipeline steps"""
        steps = [
            {
                'step': 1,
                'name': 'Handle Missing Values',
                'description': 'Impute missing numeric values with median, categorical with mode',
                'applied_to': f'Numeric ({len(self.numeric_cols)}) + Categorical ({len(self.categorical_cols)}) columns'
            },
            {
                'step': 2,
                'name': 'Feature Scaling',
                'description': 'Standardize numeric features (mean=0, std=1)',
                'applied_to': f'{len(self.numeric_cols)} numeric columns'
            },
            {
                'step': 3,
                'name': 'Categorical Encoding',
                'description': 'One-Hot Encoding for categorical variables',
                'applied_to': f'{len(self.categorical_cols)} categorical columns'
            },
            {
                'step': 4,
                'name': 'Model Training',
                'description': 'Train RandomForest on preprocessed features',
                'applied_to': 'All processed features'
            }
        ]
        return steps
    
    @staticmethod
    def generate_advanced_pipeline_code() -> str:
        """Generate advanced pipeline with feature selection"""
        code = '''
# ============================================
# ADVANCED PIPELINE WITH FEATURE SELECTION
# ============================================

from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.impute import KNNImputer

advanced_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('feature_selection', SelectKBest(f_classif, k=10)),  # Select top 10 features
    ('model', RandomForestClassifier(
        n_estimators=200,
        max_depth=10,
        min_samples_split=5,
        random_state=42,
        n_jobs=-1
    ))
])
'''
        return code
    
    @staticmethod
    def generate_cross_validation_code() -> str:
        """Generate cross-validation evaluation code"""
        code = '''
# ============================================
# CROSS-VALIDATION EVALUATION
# ============================================

from sklearn.model_selection import cross_val_score, cross_validate

# 5-fold cross-validation
cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5, scoring='accuracy')
print(f"CV Scores: {cv_scores}")
print(f"Mean CV Score: {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

# Detailed cross-validation evaluation
scoring = {
    'accuracy': 'accuracy',
    'precision': 'precision',
    'recall': 'recall',
    'f1': 'f1'
}
cv_results = cross_validate(pipeline, X_train, y_train, cv=5, scoring=scoring)
print(f"Detailed Results: {cv_results}")
'''
        return code
